export const ROUTES = {
  home: '/',
  homeQs: (qs: string) => `/${qs}`,
  about_us: '/about-us',
  business: '/business',
  problems: '/problems',
  dorosly_temy: '/dorosly-temy',
  personalities: '/16-personalities',
  psyhologichni_testy: '/psyhologichni-testy',
  courses: '/courses',
  reviews: '/reviews',
  certificate: '/certificate',
  howItWork: '/how-it-work',
  psychologists: '/psychologists',
  psychologistsQs: (qs: string) => `/psychologists${qs}`,
  prices: '/subscription',
  offlineCenters: '/offline-centers',
  news: `/news`,
  contacts: `/contact`,
  newsSingle: (slug: string) => `/news/${slug}`,
  psychologist: (id: string | number, qs: string = '') => `/psychologists/${id}${qs}`,
  checkout: (id: string | number, qs: string = '') => `/psychologists/${id}/checkout${qs}`,
  offlineCheckout: (id: string | number) => `/psychologists/${id}/offline-order`,
  sitemap: `/sitemap`,

  cabinet: '/cabinet',
  cabinetShop: `/cabinet/subscriptions`,
  cabinetCertificate: `/cabinet/certificate`,
  cabinetTasks: `/cabinet/tasks`,
  cabinetHistorySessions: `/cabinet/history-sessions`,
  cabinetHistoryPayments: `/cabinet/history-payments`,
  cabinetNotifications: `/cabinet/notifications`,
  cabinetSettings: `/cabinet/profile`,
  zoom: `/cabinet/zoom`,
  appInGooglePlay: 'https://play.google.com/store/apps/details?id=com.holdyou',
  appInAppStore: 'https://apps.apple.com/ru/app/holdyou/id1508230097',
  agora: (id: string | number) => `/cabinet/agora?id=${id}`,
};
