import { getPshSimpleData, normalizeReviews } from '@/utils/helpers';
import { isArray, keyBy } from 'lodash';

export const data = {
  count_psychologists: 41,
  count_psychologists_junior: 6,
  psychologists: [
    {
      id: 655,
      experience_years: 10,
      ordering: 2,
      photo: {
        original: '/media/psych/psychologist_70_TRJ8Bhw.jpg',
        sm: '/media/__sized__/psych/psychologist_70_TRJ8Bhw-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/psychologist_70_TRJ8Bhw-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/psychologist_70_TRJ8Bhw-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/psychologist_70_TRJ8Bhw-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: true,
      fullname: 'Ілона Яковлева',
      description: 'Сімейний психолог, гештальт-терапевт, психолог-сексолог',
      experience: '2014-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 24,
          type: 'approaches',
          text: 'Когнітивно-поведінкова терапія (КПТ)',
          order: 0,
          is_active: true,
        },
        {
          id: 43,
          type: 'problems',
          text: 'депресія',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 3,
          type: 'problems',
          text: 'апатія, тривожність',
          order: 0,
          is_active: true,
        },
        {
          id: 11,
          type: 'problems',
          text: 'переживання горя та втрати',
          order: 0,
          is_active: true,
        },
        {
          id: 13,
          type: 'problems',
          text: 'батьківтво, вагітність',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 22,
          type: 'specialization',
          text: 'Сексолог',
          order: 0,
          is_active: true,
        },
        {
          id: 25,
          type: 'approaches',
          text: 'Гештальт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 28,
          type: 'approaches',
          text: 'Системна сімейна терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 19,
          type: 'specialization',
          text: 'Сімейний психолог',
          order: 3,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 685,
      experience_years: 7,
      ordering: 3,
      photo: {
        original: '/media/psych/temp_6oRGxf8.png',
        sm: '/media/__sized__/psych/temp_6oRGxf8-crop-c0-5__0-5-100x100.png',
        thumbnail: '/media/__sized__/psych/temp_6oRGxf8-thumbnail-450x450.png',
        md: '/media/__sized__/psych/temp_6oRGxf8-crop-c0-5__0-5-220x220.png',
        xs: '/media/__sized__/psych/temp_6oRGxf8-crop-c0-5__0-5-50x50.png',
      },
      is_junior: false,
      fullname: 'Альона Зимогляд',
      description: 'Психолог,  арт-терапевт',
      experience: '2018-01-01T00:00:00+02:00',
      filter_ids: [
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 29,
          type: 'approaches',
          text: 'Позитивна психотерапія',
          order: 0,
          is_active: true,
        },
        {
          id: 3,
          type: 'problems',
          text: 'апатія, тривожність',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 6,
          type: 'problems',
          text: 'страхи, фобії',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 51,
          type: 'approaches',
          text: 'Метафоричні асоціативні карти ( МАК)',
          order: 0,
          is_active: true,
        },
        {
          id: 47,
          type: 'approaches',
          text: 'Казкотерапія',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 30,
          type: 'approaches',
          text: 'Інший',
          order: 7,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 658,
      experience_years: 11,
      ordering: 4,
      photo: {
        original: '/media/psych/psychologist_76_HG2Uuhx.jpg',
        sm: '/media/__sized__/psych/psychologist_76_HG2Uuhx-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/psychologist_76_HG2Uuhx-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/psychologist_76_HG2Uuhx-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/psychologist_76_HG2Uuhx-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: true,
      fullname: 'Ольга Морозова',
      description: 'Практичний психолог',
      experience: '2013-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 9,
          type: 'problems',
          text: 'розлад харчової поведінки',
          order: 0,
          is_active: true,
        },
        {
          id: 43,
          type: 'problems',
          text: 'депресія',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 3,
          type: 'problems',
          text: 'апатія, тривожність',
          order: 0,
          is_active: true,
        },
        {
          id: 14,
          type: 'problems',
          text: 'кризові стани',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 27,
          type: 'approaches',
          text: 'Транзактний аналіз',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 30,
          type: 'approaches',
          text: 'Інший',
          order: 7,
          is_active: true,
        },
        {
          id: 8,
          type: 'problems',
          text: 'травма, ПТСР',
          order: 10,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 649,
      experience_years: 8,
      ordering: 5,
      photo: {
        original: '/media/psych/psychologist_60_yyJEKE8.jpg',
        sm: '/media/__sized__/psych/psychologist_60_yyJEKE8-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/psychologist_60_yyJEKE8-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/psychologist_60_yyJEKE8-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/psychologist_60_yyJEKE8-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: false,
      fullname: 'Ольга Зінченко',
      description: 'Психолог-консультант',
      experience: '2016-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 6,
          type: 'problems',
          text: 'страхи, фобії',
          order: 0,
          is_active: true,
        },
        {
          id: 11,
          type: 'problems',
          text: 'переживання горя та втрати',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 54,
          type: 'approaches',
          text: 'Символ-драма',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 659,
      experience_years: 11,
      ordering: 6,
      photo: {
        original: '/media/psych/psychologist_79_lm1RvqW.jpg',
        sm: '/media/__sized__/psych/psychologist_79_lm1RvqW-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/psychologist_79_lm1RvqW-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/psychologist_79_lm1RvqW-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/psychologist_79_lm1RvqW-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: false,
      fullname: 'Анна Булатова',
      description: 'Психолог, гештальт-терапевт',
      experience: '2013-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 25,
          type: 'approaches',
          text: 'Гештальт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 27,
          type: 'approaches',
          text: 'Транзактний аналіз',
          order: 0,
          is_active: true,
        },
        {
          id: 51,
          type: 'approaches',
          text: 'Метафоричні асоціативні карти ( МАК)',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 3,
          type: 'problems',
          text: 'апатія, тривожність',
          order: 0,
          is_active: true,
        },
        {
          id: 14,
          type: 'problems',
          text: 'кризові стани',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 21,
          type: 'specialization',
          text: 'Підлітковий психолог',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 18,
          type: 'specialization',
          text: 'Психотерапевт',
          order: 2,
          is_active: true,
        },
        {
          id: 30,
          type: 'approaches',
          text: 'Інший',
          order: 7,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 656,
      experience_years: 11,
      ordering: 7,
      photo: {
        original: '/media/psych/psychologist_72_qFEKjZ5.jpg',
        sm: '/media/__sized__/psych/psychologist_72_qFEKjZ5-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/psychologist_72_qFEKjZ5-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/psychologist_72_qFEKjZ5-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/psychologist_72_qFEKjZ5-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: true,
      fullname: 'Наталія Здоровцова',
      description: 'Психолог, сімейний психолог, сексолог',
      experience: '2013-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 10,
          type: 'problems',
          text: 'агресія, злість, почуття сорому',
          order: 0,
          is_active: true,
        },
        {
          id: 45,
          type: 'approaches',
          text: 'Психоаналіз',
          order: 0,
          is_active: true,
        },
        {
          id: 11,
          type: 'problems',
          text: 'переживання горя та втрати',
          order: 0,
          is_active: true,
        },
        {
          id: 14,
          type: 'problems',
          text: 'кризові стани',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 22,
          type: 'specialization',
          text: 'Сексолог',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 19,
          type: 'specialization',
          text: 'Сімейний психолог',
          order: 3,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
  ],
  psychologists_junior: [
    {
      id: 666,
      experience_years: 16,
      ordering: 1,
      photo: {
        original: '/media/psych/e0222dd8889d1787e320a3d85fe979ad_pPeJFMD.png',
        sm: '/media/__sized__/psych/e0222dd8889d1787e320a3d85fe979ad_pPeJFMD-crop-c0-5__0-5-100x100.png',
        thumbnail:
          '/media/__sized__/psych/e0222dd8889d1787e320a3d85fe979ad_pPeJFMD-thumbnail-450x450.png',
        md: '/media/__sized__/psych/e0222dd8889d1787e320a3d85fe979ad_pPeJFMD-crop-c0-5__0-5-220x220.png',
        xs: '/media/__sized__/psych/e0222dd8889d1787e320a3d85fe979ad_pPeJFMD-crop-c0-5__0-5-50x50.png',
      },
      is_junior: true,
      fullname: 'Ірина Салтикова',
      description: 'Практичний психолог',
      experience: '2008-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 43,
          type: 'problems',
          text: 'депресія',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 6,
          type: 'problems',
          text: 'страхи, фобії',
          order: 0,
          is_active: true,
        },
        {
          id: 3,
          type: 'problems',
          text: 'апатія, тривожність',
          order: 0,
          is_active: true,
        },
        {
          id: 13,
          type: 'problems',
          text: 'батьківтво, вагітність',
          order: 0,
          is_active: true,
        },
        {
          id: 14,
          type: 'problems',
          text: 'кризові стани',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 20,
          type: 'specialization',
          text: 'Дитячий психолог',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 30,
          type: 'approaches',
          text: 'Інший',
          order: 7,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 655,
      experience_years: 10,
      ordering: 2,
      photo: {
        original: '/media/psych/psychologist_70_TRJ8Bhw.jpg',
        sm: '/media/__sized__/psych/psychologist_70_TRJ8Bhw-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/psychologist_70_TRJ8Bhw-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/psychologist_70_TRJ8Bhw-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/psychologist_70_TRJ8Bhw-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: true,
      fullname: 'Ілона Яковлева',
      description: 'Сімейний психолог, гештальт-терапевт, психолог-сексолог',
      experience: '2014-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 11,
          type: 'problems',
          text: 'переживання горя та втрати',
          order: 0,
          is_active: true,
        },
        {
          id: 13,
          type: 'problems',
          text: 'батьківтво, вагітність',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 24,
          type: 'approaches',
          text: 'Когнітивно-поведінкова терапія (КПТ)',
          order: 0,
          is_active: true,
        },
        {
          id: 43,
          type: 'problems',
          text: 'депресія',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 3,
          type: 'problems',
          text: 'апатія, тривожність',
          order: 0,
          is_active: true,
        },
        {
          id: 22,
          type: 'specialization',
          text: 'Сексолог',
          order: 0,
          is_active: true,
        },
        {
          id: 25,
          type: 'approaches',
          text: 'Гештальт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 28,
          type: 'approaches',
          text: 'Системна сімейна терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 19,
          type: 'specialization',
          text: 'Сімейний психолог',
          order: 3,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 658,
      experience_years: 11,
      ordering: 4,
      photo: {
        original: '/media/psych/psychologist_76_HG2Uuhx.jpg',
        sm: '/media/__sized__/psych/psychologist_76_HG2Uuhx-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/psychologist_76_HG2Uuhx-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/psychologist_76_HG2Uuhx-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/psychologist_76_HG2Uuhx-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: true,
      fullname: 'Ольга Морозова',
      description: 'Практичний психолог',
      experience: '2013-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 9,
          type: 'problems',
          text: 'розлад харчової поведінки',
          order: 0,
          is_active: true,
        },
        {
          id: 43,
          type: 'problems',
          text: 'депресія',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 3,
          type: 'problems',
          text: 'апатія, тривожність',
          order: 0,
          is_active: true,
        },
        {
          id: 14,
          type: 'problems',
          text: 'кризові стани',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 27,
          type: 'approaches',
          text: 'Транзактний аналіз',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 30,
          type: 'approaches',
          text: 'Інший',
          order: 7,
          is_active: true,
        },
        {
          id: 8,
          type: 'problems',
          text: 'травма, ПТСР',
          order: 10,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 656,
      experience_years: 11,
      ordering: 7,
      photo: {
        original: '/media/psych/psychologist_72_qFEKjZ5.jpg',
        sm: '/media/__sized__/psych/psychologist_72_qFEKjZ5-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/psychologist_72_qFEKjZ5-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/psychologist_72_qFEKjZ5-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/psychologist_72_qFEKjZ5-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: true,
      fullname: 'Наталія Здоровцова',
      description: 'Психолог, сімейний психолог, сексолог',
      experience: '2013-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 11,
          type: 'problems',
          text: 'переживання горя та втрати',
          order: 0,
          is_active: true,
        },
        {
          id: 45,
          type: 'approaches',
          text: 'Психоаналіз',
          order: 0,
          is_active: true,
        },
        {
          id: 10,
          type: 'problems',
          text: 'агресія, злість, почуття сорому',
          order: 0,
          is_active: true,
        },
        {
          id: 14,
          type: 'problems',
          text: 'кризові стани',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 22,
          type: 'specialization',
          text: 'Сексолог',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 19,
          type: 'specialization',
          text: 'Сімейний психолог',
          order: 3,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
    {
      id: 673,
      experience_years: 9,
      ordering: 13,
      photo: {
        original: '/media/psych/f7eb4c4306004ae732dc0d0ff5098605_hxChEEZ.jpg',
        sm: '/media/__sized__/psych/f7eb4c4306004ae732dc0d0ff5098605_hxChEEZ-crop-c0-5__0-5-100x100-80.jpg',
        thumbnail:
          '/media/__sized__/psych/f7eb4c4306004ae732dc0d0ff5098605_hxChEEZ-thumbnail-450x450-80.jpg',
        md: '/media/__sized__/psych/f7eb4c4306004ae732dc0d0ff5098605_hxChEEZ-crop-c0-5__0-5-220x220-80.jpg',
        xs: '/media/__sized__/psych/f7eb4c4306004ae732dc0d0ff5098605_hxChEEZ-crop-c0-5__0-5-50x50-80.jpg',
      },
      is_junior: true,
      fullname: 'Антон Козаченко',
      description: 'Практичний психолог, гештальт-терапевт',
      experience: '2015-12-23T00:00:00+02:00',
      filter_ids: [
        {
          id: 6,
          type: 'problems',
          text: 'страхи, фобії',
          order: 0,
          is_active: true,
        },
        {
          id: 11,
          type: 'problems',
          text: 'переживання горя та втрати',
          order: 0,
          is_active: true,
        },
        {
          id: 15,
          type: 'problems',
          text: 'взаємовідносини',
          order: 0,
          is_active: true,
        },
        {
          id: 25,
          type: 'approaches',
          text: 'Гештальт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 26,
          type: 'approaches',
          text: 'Арт-терапія',
          order: 0,
          is_active: true,
        },
        {
          id: 54,
          type: 'approaches',
          text: 'Символ-драма',
          order: 0,
          is_active: true,
        },
        {
          id: 10,
          type: 'problems',
          text: 'агресія, злість, почуття сорому',
          order: 0,
          is_active: true,
        },
        {
          id: 3,
          type: 'problems',
          text: 'апатія, тривожність',
          order: 0,
          is_active: true,
        },
        {
          id: 44,
          type: 'problems',
          text: 'самооцінка та самоцінність',
          order: 0,
          is_active: true,
        },
        {
          id: 17,
          type: 'specialization',
          text: 'Психолог',
          order: 1,
          is_active: true,
        },
        {
          id: 18,
          type: 'specialization',
          text: 'Психотерапевт',
          order: 2,
          is_active: true,
        },
        {
          id: 8,
          type: 'problems',
          text: 'травма, ПТСР',
          order: 10,
          is_active: true,
        },
        {
          id: 5,
          type: 'problems',
          text: 'втома, емоційне вигорання',
          order: 15,
          is_active: true,
        },
        {
          id: 16,
          type: 'problems',
          text: 'інше',
          order: 30,
          is_active: true,
        },
      ],
    },
  ],
  categories_problems: [
    {
      id: 2,
      image: {
        thumbnail:
          '/media/__sized__/main-page/categories/Frame_43-thumbnail-505x477.png',
        original: '/media/main-page/categories/Frame_43.png',
      },
      image2: {
        thumbnail:
          '/media/__sized__/main-page/categories/IMG20240501103141_lYErAza-thumbnail-505x477-80.jpg',
        original: '/media/main-page/categories/IMG20240501103141_lYErAza.jpg',
      },
      name: 'Емоційне вигорання ID:2',
      text: "<p><strong>Емоційне вигорання — це психічне, емоційне і фізичне виснаження, яке виникає від перевантаження, тривалого стресу або безперервної напруги в сфері, що вимагає від Вас високого рівня емоційних зусиль.</strong></p>\r\n    <p>Людина, що відчуває емоційне вигорання, постійно втомлена, втрачає мотивацію до будь-яких справ, навіть раніше цікавих для неї.</p>\r\n    <p>Такий стан спричиняє порушення не лише Вашого внутрішнього балансу,  а може негативно впливати і на Ваше оточення або мати руйнівні наслідки для кар'єри.</p>\r\n    <h5>Про емоційне вигорання можна говорити якщо:</h5>\r\n    <p>\r\n    - сон або відпочинок не приносять бадьорості та енергії;<br />\r\n    - погіршилося фізичне самопочуття, з'явилися головні болі, проблеми зі сном, знизилася концентрація уваги або пам'ять;<br />\r\n    - періодично нізвідки з'являється почуття тривоги, безсилля, суму, відчувається безсилля або втрата надії;<br />\r\n    - практично нічого не приносить радості та задоволення;<br />\r\n    - весь час хочеться відпочити, пропала мотивація для дій, людина прагне ізоляції від суспільства;<br />\r\n    - раніше чуйна і привітна людина стає замкнутою, іноді навіть цинічною, неефективно виконує роботу.<br />\r\n    </p>\r\n    <p><strong>Емоційне вигорання це серйозний стан, але за допомогою спеціалістів-психологів та небайдужого оточення він піддається ефективній (хоча іноді і не дуже швидкій) корекції.</strong></p>",
      questionnaire_frame: `<div data-tf-widget="s0RkUCvS" data-tf-iframe-props="title=Тест для підлітків" data-tf-transitive-search-params data-tf-medium="snippet" style="width:100%;height:500px;"></div><script src="//embed.typeform.com/next/embed.js"></script>`,
      ordering: 2,
      psychology_ids: [655, 658, 649, 659, 656],
      article_ids: [1104, 1599, 1595, 1593, 1591],
      feedback_ids: [995, 996, 997, 998, 999, 1000],
    },
    {
      id: 1,
      image: {
        thumbnail:
          '/media/__sized__/main-page/categories/IMG20240501103141_lYErAza-thumbnail-505x477-80.jpg',
        original: '/media/main-page/categories/IMG20240501103141_lYErAza.jpg',
      },
      name: 'Name UK ID:1',
      text: 'Text UK',
      questionnaire_frame: `<div data-tf-widget=\"GESrrIEJ\" data-tf-opacity=\"100\" data-tf-iframe-props=\"title=My typeform\" data-tf-transitive-search-params=\"\" data-tf-medium=\"snippet\" style=\"width:100%;height:500px;\" data-tf-loaded=\"true\"><div class=\"tf-v1-widget\" data-testid=\"tf-v1-widget\"><iframe src=\"https://form.typeform.com/to/GESrrIEJ?typeform-embed-id=8636459250962212&amp;typeform-embed=embed-widget&amp;typeform-source=localhost&amp;typeform-medium=snippet&amp;typeform-medium-version=next&amp;embed-opacity=100&amp;typeform-embed-no-heading=true\" data-testid=\"iframe\" allow=\"microphone; camera\" title=\"My typeform\" style=\"border: 0px;\"></iframe></div></div><script src=\"//embed.typeform.com/next/embed.js\"></script>`,
      ordering: 10,
      psychology_ids: [655, 685],
      article_ids: [1587, 1585],
      feedback_ids: [990],
    },
  ],
  articles: [
    {
      id: 1104,
      preview: {
        thumbnail:
          '/media/__sized__/pages/POST/None/2023/11/news_82_JpGhndt-thumbnail-700x340-80.jpg',
        original: '/media/pages/POST/None/2023/11/news_82_JpGhndt.jpg',
      },
      slug: 'platforma-dlya-psikhologov',
      title:
        'Платформа для психологів. Чому ми вирішуємо відразу кілька проблем в пошуку фахівця?',
      description:
        'Тут розповімо про переваги сервісу, чому онлайн терапія ефективна і як записатися на консультацію.',
      created: '2023-11-14T14:41:01.798574+02:00',
    },
    {
      id: 1599,
      preview: {
        thumbnail:
          '/media/__sized__/pages/POST/None/2024/08/Psikholog_servisa_HoldYou-thumbnail-700x340.png',
        original:
          '/media/pages/POST/None/2024/08/Psikholog_servisa_HoldYou.png',
      },
      slug: 'psiholog-lviv-onlajn',
      title: 'Психолог Львів онлайн',
      description:
        'Якщо ви відчуваєте, що потребуєте підтримки й допомоги спеціаліста, то негайно зверніться за онлайн консультацією до психологів HoldYou',
      created: '2024-08-03T10:53:52.413042+03:00',
    },
    {
      id: 1595,
      preview: {
        thumbnail:
          '/media/__sized__/pages/POST/None/2024/07/Onlayn_konsul%CA%B9tatsiya_psykholoha_HoldYou-thumbnail-700x340.png',
        original:
          '/media/pages/POST/None/2024/07/Onlayn_konsul%CA%B9tatsiya_psykholoha_HoldYou.png',
      },
      slug: 'chomu-bezkoshtovna-onlajn-konsultatsya-u-psihologa',
      title: 'Чому безкоштовна психологічна допомога не завжди допомагає?',
      description:
        'Платна та безкоштовна онлайн консультація мають розбіжність між собою, інколи навіть дуже значну.',
      created: '2024-07-23T11:26:45.528880+03:00',
    },
    {
      id: 1593,
      preview: {
        thumbnail:
          '/media/__sized__/pages/POST/None/2024/07/Prychyny-rozpadu-stosunkiv-news-HoldYou-thumbnail-700x340.png',
        original:
          '/media/pages/POST/None/2024/07/Prychyny-rozpadu-stosunkiv-news-HoldYou.png',
      },
      slug: 'chomu-cholovki-vd-mene-vtkayut',
      title: '“Чому чоловіки від мене втікають?”: причини розпаду стосунків',
      description:
        'На різних етапах стосунків можуть виникати відмінності в цілях і цінностях, що призводить до різних поглядів на майбутнє.',
      created: '2024-07-21T10:57:22.549136+03:00',
    },
    {
      id: 1591,
      preview: {
        thumbnail:
          '/media/__sized__/pages/POST/None/2024/07/Despotychni-bat%CA%B9ky-novyna-HoldYou-thumbnail-700x340.png',
        original:
          '/media/pages/POST/None/2024/07/Despotychni-bat%CA%B9ky-novyna-HoldYou.png',
      },
      slug: 'ya-hochu-abi-moya-ditina-bula-sluhnyanoyu',
      title:
        '“Я хочу, аби моя дитина була слухняною”. Хто такі деспотичні батьки та які наслідки такого виховання?',
      description:
        'Вони вважають, що їхнє слово має бути законом, не допускають жодних відхилень від встановлених ними правил та не прагнуть знайти контакт з власною дитиною.',
      created: '2024-07-15T11:17:43.531101+03:00',
    },
    {
      id: 1587,
      preview: {
        thumbnail:
          '/media/__sized__/pages/POST/None/2024/07/%D0%A4%D0%BE%D1%82%D0%BE_%D0%B4%D0%BE_%D1%81%D1%82%D0%B0%D1%82%D0%B5%D0%B9_20-thumbnail-700x340.png',
        original:
          '/media/pages/POST/None/2024/07/%D0%A4%D0%BE%D1%82%D0%BE_%D0%B4%D0%BE_%D1%81%D1%82%D0%B0%D1%82%D0%B5%D0%B9_20.png',
      },
      slug: 'vpliv-manpulyats-ta-brehn-u-stosunkah',
      title: 'Вплив маніпуляції та брехні у стосунках',
      description:
        'Важливо вчасно розпізнавати порушення особистих кордонів, аби не потрапити у пастку, прикрашену нібито піклуванням й ніжністю.',
      created: '2024-07-10T13:03:31.665591+03:00',
    },
    {
      id: 1585,
      preview: {
        thumbnail:
          '/media/__sized__/pages/POST/None/2024/07/1212122-thumbnail-700x340.png',
        original: '/media/pages/POST/None/2024/07/1212122.png',
      },
      slug: 'scho-take-abyuzivn-stosunki',
      title: "Що таке аб'юзивні стосунки?",
      description:
        'Знайти вихід з аб’юзивних та токсичних відносин, через роботу в терапевтичній групі для залежних HoldYou',
      created: '2024-07-09T14:06:14.843024+03:00',
    },
  ],
  feedbacks: [
    {
      id: 1000,
      user: {
        id: 88494,
        fullname: 'Ольга Нагайчук',
      },
      comment: 'Дуже цінно. Багато інсайтів.',
    },
    {
      id: 999,
      user: {
        id: 88494,
        fullname: 'Ольга Нагайчук',
      },
      comment: 'Дуже мене відчула і мою ситуацію',
    },
    {
      id: 998,
      user: {
        id: 88545,
        fullname: 'Дмитрий',
      },
      comment: 'Неожиданный для меня, но очень классный подход!',
    },
    {
      id: 997,
      user: {
        id: 88495,
        fullname: 'Ольга',
      },
      comment: 'Все добре)',
    },
    {
      id: 996,
      user: {
        id: 88451,
        fullname: 'Дарья',
      },
      comment: 'Дякую за сесію 🥰',
    },
    {
      id: 995,
      user: {
        id: 84159,
        fullname: 'Kateryna',
      },
      comment:
        'Дякуя пані Алісо, за такі приємні зустрічі після котрих я виходжу наповненою та ще з більшим розумінням себе',
    },
    {
      id: 990,
      user: {
        id: 88451,
        fullname: 'Дарья',
      },
      comment: 'Перша сесія пройшла чудово, хочу і на далі з вами працювати ☺️',
    },
  ],
};

const feedbacksNormalized = isArray(data?.feedbacks) ? data?.feedbacks?.map(normalizeReviews) : [];
const psychologistsNormalized = isArray(data?.psychologists) ? data?.psychologists?.map(getPshSimpleData) : [];
const categoriesNormalized = isArray(data?.categories_problems) ? data?.categories_problems?.sort((a: any, b: any) => a - b) : [];
const articlesNormalized = isArray(data?.articles) ? data?.articles : [];
const psychologistsJuniorNormalized = isArray(data?.psychologists_junior) ? data?.psychologists_junior?.map(getPshSimpleData) : [];
const mainData = {
  ...data,
  categories_problems: categoriesNormalized,
  psychologists: keyBy(psychologistsNormalized, (e: any) => e.id),
  articles: keyBy(articlesNormalized, (e: any) => e.id),
  feedbacks: keyBy(feedbacksNormalized, (e: any) => e.id),
  psychologists_junior: psychologistsJuniorNormalized,
};

export { mainData };
